# Generated by Django 5.1.1 on 2024-09-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('other_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.JSONField()),
                ('job_position', models.JSONField()),
                ('education_background', models.JSONField()),
                ('resume', models.FileField(upload_to='resumes/')),
                ('references', models.JSONField()),
            ],
        ),
    ]
