# Generated by Django 5.1.1 on 2024-09-09 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=255)),
                ('graduation_year', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('responsibilities', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='jobapplication',
            old_name='education_background',
            new_name='cover_letters',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='job_position',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='references',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='include_other_name',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='other_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='education',
            field=models.ManyToManyField(related_name='applications', to='jobapp.education'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='experience',
            field=models.ManyToManyField(related_name='applications', to='jobapp.experience'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job_positions',
            field=models.ManyToManyField(related_name='applications', to='jobapp.jobposition'),
        ),
    ]
