# Generated by Django 5.1.1 on 2024-09-09 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0002_education_experience_jobposition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='cover_letters/')),
                ('text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='cover_letters',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='cover_letters',
            field=models.ManyToManyField(blank=True, to='jobapp.coverletter'),
        ),
    ]
